name: Release Workflow

on:
  release:
    types:
      - created

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Pre-Build Step
        # 引用 pre-build 步骤的别名
        <<: *pre-build

      - name: Job 1 Step
        # 在这里定义 job1 的具体操作
        # ...

      - name: Post-Build Step
        # 引用 post-build 步骤的别名
        <<: *post-build

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Pre-Build Step
        # 引用 pre-build 步骤的别名
        <<: *pre-build

      - name: Job 2 Step
        # 在这里定义 job2 的具体操作
        # ...

      - name: Post-Build Step
        # 引用 post-build 步骤的别名
        <<: *post-build

# 定义 pre-build 步骤的锚点和别名
pre-build: &pre-build
  - name: Pre-Build Step
    # 在这里定义 pre-build 步骤的具体操作
    # ...

# 定义 post-build 步骤的锚点和别名
post-build: &post-build
  - name: Post-Build Step
    # 在这里定义 post-build 步骤的具体操作
    # ...