steps:

  - name: Packaging
    # 即使在 windows 中执行 github action，也不需要提前安装 tar，已内置。
    # 以下针对 program_version 的警告可忽略，只要保证前面确实在环境变量中有所定义。
    # run: tar czf  ${{ matrix.artifactname }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.program_version }}.tgz ${{ matrix.artifactname }}${{ matrix.artifactext }}
    run: zip -r ${{ matrix.artifactname }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.program_version }}.zip ${{ matrix.artifactname }}${{ matrix.artifactext }}

  - name: Create GitHub release from tag
    uses: softprops/action-gh-release@v1
    with:
      files: |
        *.zip
        