steps:

  - name: Get Tag Version
    id: get_version_new
    # 首先将  ${{ github.ref }}  的值赋给  tag_name  变量。
    # 然后，使用字符串截取功能 tag_name=${tag_name#refs/tags/} 来移除 tag_name 中的前缀 "refs/tags/"。
    # 最后将其保存到环境变量 program_version 中。
    run: |
        tag_name=${{ github.ref }}
        tag_name=${tag_name#refs/tags/}
        echo "program_version=${tag_name}" >> $GITHUB_ENV

  - name: Checkout
    uses: actions/checkout@v3

  - name: Update go.sum
    run: go mod tidy

  - name: Setup Go
    uses: actions/setup-go@v3
    with:
      go-version: ">=1.18.0"
      cache: true
