name: Create release from new tag

# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  # 为 windows 和 macos 分别建立了 job。因为其所需的 runs-on 不同。
  # 但有许多 step 实际上是相同的，如 'Get Tag Version'、'Checkout'、'Update go.sum'、'Packaing' 等。
  # 可试了许久也未能成功共享这些步骤。即使将它们单独放在一个 yaml 文件中也不行。只能先重复着吧。
  build-windows:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        # 定义生成目标的操作系统的相关变量，即使有重复，也要分别定义，如 goarch。
        include:
          - goos: windows
            artifactext: ".exe"
            os: windows-latest
            # 因为不同平台用的内容相同，所以也可以使用 env 定义在外层，但集中一起更直观。
            artifactname: "vssc"
            goarch: amd64

    steps:
      - name: Get Tag Version
        id: get_version_new
        # 首先将  ${{ github.ref }}  的值赋给  tag_name  变量。
        # 然后，使用字符串截取功能 tag_name=${tag_name#refs/tags/} 来移除 tag_name 中的前缀 "refs/tags/"。
        # 最后将其保存到环境变量 program_version 中。
        run: |
            tag_name=${{ github.ref }}
            tag_name=${tag_name#refs/tags/}
            echo "program_version=${tag_name}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      # 比较有意思的是，作为代码洁癖患者，我将 go.sum 放到 .gitignore 中了，反正每次若依赖有变化，
      # 都要通过 go mod tidy 命令更新。
      # 没想到的是，如果不先执行 go mod tidy 命令，在执行后面的 Setup Go 命令时，会报：
      # Dependencies file is not found in /home/runner/work/vssetup-cleaner/vssetup-cleaner. 
      # Supported file pattern: go.sum
      # 所以还得将 Update go sum 移到此处。有趣的是，还没 Setup Go 呢，已经要执行 go mod tidy 命令了，而且还成功了。
      # 看着多少有些别扭，还是将 go.sum 加回到库中而将本 step 放到 Setup Go 之后吧。
      # - name: Update go.sum
      #   run: go mod tidy

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          cache: true

      - name: Update go.sum
        run: go mod tidy

      - name: Build for windows
        if: matrix.goos == 'windows'
        run: go build -o ${{ matrix.artifactname }}${{ matrix.artifactext }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
      
      - name: Packaging
        # 即使在 windows 中执行 github action，也不需要提前安装 tar，已内置。
        # 以下针对 program_version 的警告可忽略，只要保证前面确实在环境变量中有所定义。
        # run: tar czf  ${{ matrix.artifactname }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.program_version }}.tgz ${{ matrix.artifactname }}${{ matrix.artifactext }}
        run: zip -r ${{ matrix.artifactname }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.program_version }}.zip ${{ matrix.artifactname }}${{ matrix.artifactext }}

      - name: Create GitHub release from tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip

  build-macos:
    runs-on: macos-latest

    permissions:
      contents: write

    strategy:
      matrix:
        # 定义生成目标的操作系统的相关变量，即使有重复，也要分别定义，如 goarch。
        include:
          - goos: macos
            artifactext: ""
            os: macos-latest
            artifactname: "vssc"
            goarch: arm64

    steps:
      - name: Get Tag Version
        id: get_version_new
        # 首先将  ${{ github.ref }}  的值赋给  tag_name  变量。
        # 然后，使用字符串截取功能 tag_name=${tag_name#refs/tags/} 来移除 tag_name 中的前缀 "refs/tags/"。
        # 最后将其保存到环境变量 program_version 中。
        run: |
            tag_name=${{ github.ref }}
            tag_name=${tag_name#refs/tags/}
            echo "program_version=${tag_name}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          cache: true

      - name: Update go.sum
        run: go mod tidy
  
      - name: Build for macOS amd64
        if: matrix.goos == 'macos' && matrix.goarch == 'amd64'  
        run: go build -o ${{ matrix.artifactname }}${{ matrix.artifactext }}

      - name: Build for macOS arm64 
        if: matrix.goos == 'macos' && matrix.goarch == 'arm64'
        env:
            CC: o64-clang
            CXX: o64-clang++ 
        run: go build -o ${{ matrix.artifactname }}${{ matrix.artifactext }}
      
      - name: Packaging
        # 即使在 windows 中执行 github action，也不需要提前安装 tar，已内置。
        # 以下针对 program_version 的警告可忽略，只要保证前面确实在环境变量中有所定义。
        # run: tar czf  ${{ matrix.artifactname }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.program_version }}.tgz ${{ matrix.artifactname }}${{ matrix.artifactext }}
        run: zip -r ${{ matrix.artifactname }}-${{ matrix.goos }}-${{ matrix.goarch }}-${{ env.program_version }}.zip ${{ matrix.artifactname }}${{ matrix.artifactext }}

      - name: Create GitHub release from tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
